create table wallets (
    id             uuid         primary key,
    owner_id       varchar(64)  not null,
    currency       varchar(3)   not null,
    balance_minor  bigint       not null,
    status         varchar(16)  not null,
    version        bigint       not null,
    created_at     timestamp with time zone not null,
    updated_at     timestamp with time zone not null,
    constraint uq_wallet_owner_currency unique (owner_id, currency),
    constraint ck_wallet_balance_non_negative check (balance_minor >= 0)
);

create table transfers (
    id                uuid        primary key,
    source_wallet_id  uuid        not null references wallets (id),
    target_wallet_id  uuid        not null references wallets (id),
    amount_minor      bigint      not null,
    fee_minor         bigint      not null,
    currency          varchar(3)  not null,
    refunded_minor    bigint      not null,
    status            varchar(24) not null,
    version           bigint      not null,
    created_at        timestamp with time zone not null,
    constraint ck_transfer_amount_positive check (amount_minor > 0),
    constraint ck_transfer_fee_non_negative check (fee_minor >= 0),
    constraint ck_transfer_refund_bounds check (refunded_minor >= 0 and refunded_minor <= amount_minor),
    constraint ck_transfer_distinct_wallets check (source_wallet_id <> target_wallet_id)
);

create table ledger_entries (
    id                   bigint generated by default as identity primary key,
    transaction_id       uuid        not null,
    wallet_id            uuid        not null references wallets (id),
    entry_type           varchar(32) not null,
    amount_minor         bigint      not null,
    balance_after_minor  bigint      not null,
    transfer_id          uuid,
    created_at           timestamp with time zone not null,
    constraint ck_ledger_amount_non_zero check (amount_minor <> 0)
);

create index ix_ledger_wallet_id_id on ledger_entries (wallet_id, id);
create index ix_ledger_transaction on ledger_entries (transaction_id);

create table idempotency_keys (
    idempotency_key  varchar(64)   primary key,
    operation        varchar(64)   not null,
    request_hash     varchar(64)   not null,
    response_status  int           not null,
    response_body    varchar(8192),
    created_at       timestamp with time zone not null
);
