package com.example.wallet.domain;

public enum ErrorCode {
    WALLET_NOT_FOUND(Kind.NOT_FOUND),
    TRANSFER_NOT_FOUND(Kind.NOT_FOUND),

    WALLET_ALREADY_EXISTS(Kind.CONFLICT),
    INVALID_STATUS_TRANSITION(Kind.CONFLICT),
    REQUEST_IN_PROGRESS(Kind.CONFLICT),

    INSUFFICIENT_FUNDS(Kind.UNPROCESSABLE),
    WALLET_NOT_ACTIVE(Kind.UNPROCESSABLE),
    WALLET_NOT_EMPTY(Kind.UNPROCESSABLE),
    CURRENCY_MISMATCH(Kind.UNPROCESSABLE),
    UNSUPPORTED_CURRENCY(Kind.UNPROCESSABLE),
    AMOUNT_LIMIT_EXCEEDED(Kind.UNPROCESSABLE),
    DAILY_LIMIT_EXCEEDED(Kind.UNPROCESSABLE),
    REFUND_EXCEEDS_TRANSFER(Kind.UNPROCESSABLE),
    IDEMPOTENCY_KEY_REUSED(Kind.UNPROCESSABLE),
    SAME_WALLET_TRANSFER(Kind.UNPROCESSABLE),
    SYSTEM_WALLET_NOT_ALLOWED(Kind.UNPROCESSABLE),
    BALANCE_OVERFLOW(Kind.UNPROCESSABLE);

    public enum Kind {
        NOT_FOUND,
        CONFLICT,
        UNPROCESSABLE
    }

    private final Kind kind;

    ErrorCode(Kind kind) {
        this.kind = kind;
    }

    public Kind kind() {
        return kind;
    }
}
