spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:20}

logging:
  structured:
    format:
      console: ecs

management:
  endpoint:
    health:
      show-details: when-authorized
